# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs



name: config2.js CI

on:
  push:
    branches: [ "main" ]
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
        
    - name: Install backend
      run: npm install
      working-directory: hub-de-leitura-integrado

    - name: Start backend
      run: npm start &
      working-directory: hub-de-leitura-integrado

    - name: Install UI dependencies
      run: npm install
      working-directory: QA-projeto-de-automacao-de-UI
    
    - name: Wait for backend
      run: npx wait-on http://localhost:3000 --timeout 60000
      working-directory: QA-projeto-de-automacao-de-UI
    
    - name: Run Cypress
      run: npx cypress run
      working-directory: QA-projeto-de-automacao-de-UI
